version: 2
jobs:
  build:
    working_directory: ~/api.getnativelearning.com

    docker:
      - image: circleci/ruby:2.3-node
        environment:
          - NODE_ENV: circle_ci
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_USER: getnative
          - MYSQL_PASSWORD: getnative
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: getnative_test

    branches:
      only:
        - master
        - develop

    steps:
      - checkout

      - run:
          name: Install System Dependencies
          command: |
              sudo apt-get update -y
              sudo apt-get install -y build-essential libav-tools
  
      - restore_cache:
          keys:
              - api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}

      - run:
          name: Install Node Dependencies
          command: |
              node --version
              npm --version
              npm install

      - save_cache:
          key: api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: .circleci/generate-jwt-keypair.sh

      - run:
          name: Migrate Database
          command: cp config/database.json.template config/database.json && npm run sequelize db:migrate

      - run: npm test

      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    git clone git@github.com:hank-ehly/devops.getnativelearning.com.git
                    cd devops.getnativelearning.com/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:staging deploy
              elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git clone git@github.com:hank-ehly/devops.getnativelearning.com.git
                    cd devops.getnativelearning.com/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:production deploy
              fi
