version: 2
jobs:
  build:
    working_directory: ~/api.getnativelearning.com
    docker:
      - image: circleci/node:latest
        environment:
          - NODE_ENV: test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_USER: get_native
          - MYSQL_PASSWORD: get_native
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: get_native_test
    branches:
      only:
        - master
        - develop
    steps:
      - checkout
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y build-essential libav-tools
      - run:
          name: Install ruby
          command: |
              if [ ! -d /home/circleci/.rbenv ]; then
                  git clone https://github.com/sstephenson/rbenv.git ~/.rbenv
                  git clone https://github.com/sstephenson/ruby-build.git ~/.rbenv/plugins/ruby-build
                  echo 'export PATH="$HOME/.rbenv/bin:$PATH"' >> ${HOME}/.profile
                  echo 'eval "$(rbenv init -)"' >> ${HOME}/.profile
                  source ${HOME}/.profile
                  rbenv install --verbose 2.3.1
                  rbenv global 2.3.1 && ruby -v
                  gem install bundler
              fi
      - restore_cache:
          keys:
              - api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}
              - ruby-cache
      - run: npm install
      - save_cache:
          key: api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - save_cache:
          key: ruby-cache
          paths:
            - "/home/circleci/.rbenv/"
      - run: ./bin/generate-jwt-keypair.bash
      - run:
          name: Setup DB
          command: |
            cp config/database.json.template config/database.json
            npm run sequelize db:migrate
      - run: npm test
      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    git clone git@github.com:hank-ehly/devops.getnativelearning.com.git
                    cd devops.getnativelearning.com/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:staging deploy
              elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git clone git@github.com:hank-ehly/devops.getnativelearning.com.git
                    cd devops.getnativelearning.com/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:production deploy
              fi
