version: 2
jobs:
  build:
    docker:
      - image: circleci/node:latest
        environment:
          - NODE_ENV: test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_USER: get_native
          - MYSQL_PASSWORD: get_native
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: get_native_test
    branches:
      only:
        - master
        - develop
    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y build-essential libav-tools

      - run:
          name: Update NPM
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install node modules
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules

      - run:
          name: Generate JWT keypair
          command: ./bin/generate-jwt-keypair.bash

      - run:
          name: Setup DB
          command: |
            cp config/database.json.template config/database.json
            npm run sequelize db:migrate

      - run:
          name: Test
          command: npm test

      - deploy:
          name: Deploy
          command: |
            git clone git@github.com:hank-ehly/get-native.com-devops.git
            if [ "${CIRCLE_BRANCH}" == "develop" ]; then
              cd get-native.com-devops/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:staging deploy
            elif [ "${CIRCLE_BRANCH}" == "master" ]; then
              cd get-native.com-devops/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:production deploy
            fi
