version: 2
jobs:
  build:
    working_directory: ~/api.get-native.com
    docker:
      - image: circleci/ruby:2.3-node
        environment:
          - NODE_ENV: test
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_USER: get_native
          - MYSQL_PASSWORD: get_native
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: get_native_test
    branches:
      only:
        - master
        - develop
    steps:
      - checkout
      - run: sudo apt-get update -y
      - run: sudo apt-get install -y build-essential libav-tools
      - restore_cache:
          key: api.get-native.com-{{ .Branch }}-{{ checksum "package.json" }}
      - run: npm install
      - save_cache:
          key: api.get-native.com-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"
      - run: ./bin/generate-jwt-keypair.bash
      - run: |
          name: Setup DB
          command: |
            cp config/database.json.template config/database.json
            npm run sequelize db:migrate
      - run: npm test
      - deploy: ./bin/deploy.sh
