version: 2
jobs:
  build:
    docker:
      - image: hankehly/api.getnativelearning.com:0.0.3
        environment:
          - NODE_ENV: circle_ci
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_USER: getnative
          - MYSQL_PASSWORD: getnative
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: getnative_test

    working_directory: ~/api.getnativelearning.com

    branches:
      only:
        - master
        - develop

    steps:
      - checkout

      - restore_cache:
          keys:
              - api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run:
          name: Prepare app for testing
          command: |
            node .circleci/keygen.js config/secrets/jwt-keypair.json
            cp config/database.json.template config/database.json && npm run sequelize db:migrate

      - run: npm test

      - deploy:
          name: Deploy
          command: .circleci/deploy.sh ${CIRCLE_BRANCH}

