version: 2
jobs:
  build:
    docker:
      - image: hankehly/api.getnativelearning.com:0.0.2
        environment:
          - NODE_ENV: circle_ci
      - image: circleci/mysql:5.7
        environment:
          - MYSQL_ALLOW_EMPTY_PASSWORD: yes
          - MYSQL_USER: getnative
          - MYSQL_PASSWORD: getnative
          - MYSQL_ROOT_HOST: "%"
          - MYSQL_DATABASE: getnative_test

    working_directory: ~/api.getnativelearning.com

    branches:
      only:
        - master
        - develop

    steps:
      - checkout

      - restore_cache:
          keys:
              - api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          key: api.getnativelearning.com-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - "node_modules"

      - run: .circleci/generate-jwt-keypair.sh

      - run:
          name: Migrate Database
          command: cp config/database.json.template config/database.json && npm run sequelize db:migrate

      - run: npm test

      - deploy:
          name: Deploy
          command: |
              if [ "${CIRCLE_BRANCH}" == "develop" ]; then
                    git clone git@github.com:hank-ehly/devops.getnativelearning.com.git
                    cd devops.getnativelearning.com/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:staging deploy
              elif [ "${CIRCLE_BRANCH}" == "master" ]; then
                    git clone git@github.com:hank-ehly/devops.getnativelearning.com.git
                    cd devops.getnativelearning.com/deploy && bundle install --jobs 4 --retry 3 --path vendor/bundle && bundle exec cap server:production deploy
              fi
